### ISSUE TITLE
Question: how to interact with native controls

### ISSUE THREAD

**Issue by joeblew99** [dskinner/material#11]
This is really nice package to use.
It's a opengl runtime in essence.

I am wondering if any thought has been given to the use cases of when a develop need to incorporate / invoke native controls such as a calendar widget etc ?

I am thinking that a bridge using gomobile could work but really guessing here. Hence why I am asking.

And I also read on the readme that this project is scoped only to the material design aspects. I am asking because I am looking at doing this work myself

**Comment by dskinner** [comment]
Access to native controls wouldn't be feasible since the project intends to span multiple platforms including desktop and mobile. Instead, one would have to build the widget with the yet-to-be provided components in this package.

For example, a date picker might be made with regards to the following:
https://www.google.com/design/spec/components/grid-lists.html
https://www.google.com/design/spec/components/dialogs.html

Or, one may be building a calendar and that is simply list, such as in the official Google calendar app on mobile:
https://www.google.com/design/spec/components/lists.html

So, this project isn't concerned with such things as a calendar widget, but it is heavily concerned with being able to write a calendar widget as simply as possible that works well as-is across mobile and desktop.

With that said, a nice set of common widgets such as the calendar is pretty much a must, but that would be a separate project building on this one.

**Comment by joeblew99** [comment]
@dskinner 
I can understand the architectural direction your going. Thanks for the heads up.
I will likely go for the Angular 2 material UI for the current project, as i have more immediate needs.

Will close as this answers my query.
